version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            python -m venv nummer-env
            source nummer-env/bin/activate
            pip install -r requirements.txt
          name: Install Dependencies
      - run:
          command: |
            sudo pip install coverage coveralls
            coverage run --source=./nummer_games -m unittest test.py
            coverage report -m
            coveralls
          name: Run test with coverage
