version: 2

jobs:
  build:
    working_directory: ~/number-game

machine:
  python:
    version: 3.5.2

dependencies:
  override:
    - pip install -r requirements.txt

test:
  override:
    - python -m unittest test.py

post:
    - coverage run --source=./nummer_games -m unittest test.py
    - coverage report -m
    - coveralls